### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by dwhitacre** [dwhitacre/WindowsGSM.ForgeMC#1]
This plugin is currently a WIP. This is a list of what needs done to have an 1.0 release.

## Todo
- [x] install latest MC Forge
- [x] start a MC forge server
- [x] stop a MC forge server
- [x] update an existing forge server
- [x] validate an existing forge install
- [x] validate an import of a forge server
- [x] be able to get local version of forge server
- [x] be able to get latest remote version of forge server

**Comment by dwhitacre** [comment]
done!
